version: "3"

services:
  webserver_service_a:
    build: 
      context: ./dockerfiles/webserver
    container_name: 'webserver_name_a'
    restart: 'no'
    ports:
     - "1080:80"
#     - "1443:443"
    links: 
      - database_service_ab
    volumes: 
      - ../../../:/var/www/html
      - ./volumes/vhosts:/etc/apache2/sites-enabled
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    command:
      # this will be run by sh with a pwd of /var/www/html
      - vendor/emteknetnz/legion/commands/script-a.sh
  database_service_ab:
    build: ./dockerfiles/database
    container_name: 'database_name_ab'
    restart: 'no'
#    ports:
#      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

# start container
# docker-compose -f vendor/emteknetnz/legion/docker-compose-a.yml up

# ssh in to webserver
# docker exec -it $(docker ps -q --filter "name=webserver_name_a") bash

# connect to mysql from websever
# mysql -uroot -proot -h database

# TODO: once this thing is stable, save it as an image and host on docker hub
