version: "3"

services:
  webserver_service_b:
    build: 
      context: ./dockerfiles/webserver
    container_name: 'webserver_name_b'
    restart: 'no'
    links: 
      - database_service_ab
    volumes: 
      # These are shared from Host to B, not from A to B
      # I don't beleive it's because of docker.sock, I think it's just how things are
      - ./../../../:/var/www/html
      - ./volumes/vhosts:/etc/apache2/sites-enabled
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    command: 
      # this will be run by sh with a pwd of /var/www/html
      - vendor/emteknetnz/legion/commands/script-b.sh
  database_service_ab:  
    build: ./dockerfiles/database
    container_name: 'database_name_ab'
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: root

# start containerphp
# docker-compose -f vendor/emteknetnz/legion/docker-compose-b.yml up
