version: "3"

services:
  webserver:
    build: 
      context: ./dockerfiles/webserver
    container_name: 'legion_a_webserver'
    restart: 'no'
    ports:
     - "1080:80"
#     - "1443:443"
    links: 
      - database
    volumes: 
      - ../../../:/var/www/html
      - ./volumes/vhosts:/etc/apache2/sites-enabled
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    command:
      # this will be run by sh with a pwd of /var/www/html
      - vendor/emteknetnz/legion/commands/script-a.sh
  database:  
    build: ./dockerfiles/database
    container_name: 'legion_a_database'
    restart: 'no'
#    ports:
#      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

# remove existing image so it gets rebuilt
# docker image rm legion_a_webserver

# start container
# docker-compose -f vendor/emteknetnz/legion/docker-compose-a.yml up
# docker-compose -f docker-compose-a.yml up
# docker-compose -f docker-compose-a.yml up && docker-compose -f docker-compose-a.yml rm 
# docker-compose -f $(pwd)/vendor/emteknetnz/legion/docker-compose-a.yml up

# ssh in to webserver
# docker exec -it $(docker ps | grep legion_a_webserver | sed -n -r 's/^([^ ]+).+$/\1/p') bash

# connect to mysql from websever
# mysql -uroot -proot -h database

# TODO: once this thing is stable, save it as an image and host on docker hub
