#!/usr/bin/env php
<?php

// this file is linked automatically linked to vendor/bin/legion by composer

$dockerInstalled = true;
if (is_null(shell_exec('which docker'))) {
    echo "docker must be installed - https://docs.docker.com/install/\n";
    $dockerInstalled = false;
}

if (is_null(shell_exec('which docker-compose'))) {
    echo "docker-compose must be installed - https://docs.docker.com/compose/install/\n";
    $dockerInstalled = false;
}

if (!$dockerInstalled) {
    die;
}

// current limitation is only one instance of legion on a host machine at once
$conaexists = !is_null(shell_exec('docker ps -q --filter "name=webserver_name_a"'));

if (!$conaexists) {
    $moduledir = dirname(__FILE__);

    // up -d is pretty nice here,  it will spin it up the container detached, though
    // it will still wait for it to complete before going to the next line of php
    echo "Spinning up primary legion container, this may take a while\n";
    shell_exec("docker-compose -f $moduledir/docker-compose-a.yml up -d");
    echo "Container created\n";
    
    $conaid = trim(shell_exec('docker ps -q --filter "name=webserver_name_a"'));
    echo "Running dev/build flush=1 in container\n";
    shell_exec("docker exec $conaid bash -c 'vendor/bin/sake dev/build flush=1'");
    echo "dev/build flush=1 complete\n";
}

// run tests
if (count($argv) < 2) {
    echo "Please specify a test dir to run tests, e.g. php fromhost.php [testdir]\n";
    die;
}
$testdir = $argv[1];
$conaid = trim(shell_exec('docker ps -q --filter "name=webserver_name_a"'));
shell_exec("docker exec $conaid bash -c 'php vendor/emteknetnz/legion/runtests.php $testdir'");
